[packages]
syncthing=true
tmux=true
vim=true
alacritty=true
ripgrep=true
eza=true
zed=true
telegram-desktop=true
openssh=true
unizp=true
tar=true
firefox=true
discord=true
nushell=true
steam=true
gimp=true
godot=true
mpv=true
obs-studio=true
obsidian=true
ttf-jetbrains-mono-nerd-font=true
noto-fonts-cjk=true
# add, remove packages or change above to false

[sshgit]
type="script"
enable=true
name="nobel-von-it"
email="maksimdavydenko12@gmail.com"

[rustup]
type="script"
enable=true
analyzer=true

[zapret]
type="service"
enable=true
